import type { Metadata } from "next";
import { Geist, Nunito_Sans, Roboto_Slab, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const customText = Nunito_Sans({
  variable: "--font-custom",
  subsets: ["latin"],
});

const customTitle = Nunito_Sans({
  variable: "--font-title",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${customText.variable} ${customTitle.variable} antialiased flex flex-col justify-between min-h-screen `}
      >
        <Header />
        <div className="font-custom p-2 flex flex-col items-center">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
